# Generated by Django 4.2.20 on 2025-03-25 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('standard', models.CharField(blank=True, max_length=10, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('state', 'State Board'), ('icse', 'ICSE')], max_length=10, null=True)),
                ('condition_type', models.CharField(choices=[('none', 'None'), ('dyslexia', 'Dyslexia'), ('autism', 'Autism')], default='none', max_length=10)),
                ('conditions', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dyslexia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyslexia_type', models.CharField(blank=True, choices=[('phonological', 'Phonological'), ('surface', 'Surface'), ('visual', 'Visual')], max_length=100)),
                ('dyslexia_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100)),
                ('dyslexia_description', models.TextField(blank=True, max_length=500, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dyslexia', to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Autism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autism_type', models.CharField(blank=True, choices=[('classic', 'Classic'), ('visual', 'Visual')], max_length=100)),
                ('autism_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=100)),
                ('autism_description', models.TextField(blank=True, max_length=500, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autism', to='main.userprofile')),
            ],
        ),
    ]
