# Generated by Django 4.2.20 on 2025-03-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyslexiaTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('phonological', 'Phonological'), ('surface', 'Surface'), ('visual', 'Visual')], max_length=20)),
                ('question_type', models.CharField(choices=[('audio', 'Audio Based'), ('image', 'Image Based')], max_length=10)),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='dyslexia_test/audio/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='dyslexia_test/images/')),
                ('correct_answer', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DyslexiaTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonological_score', models.IntegerField(default=0)),
                ('surface_score', models.IntegerField(default=0)),
                ('visual_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DyslexiaTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.IntegerField(help_text='Response time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dyslexiatestquestion')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
    ]
