# Generated by Django 4.2.20 on 2025-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dyslexiatestquestion_dyslexiatestresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyslexiatestquestion',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='dyslexiatestquestion',
            name='hide_question_text',
            field=models.BooleanField(default=False, help_text='If checked, question text will only be available through text-to-speech'),
        ),
        migrations.AlterField(
            model_name='dyslexiatestquestion',
            name='question_type',
            field=models.CharField(choices=[('text_to_speech', 'Text to Speech'), ('image', 'Image Based')], max_length=20),
        ),
    ]
