# Generated by Django 4.2.20 on 2025-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_dyslexiatestquestion_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyslexiatestquestion',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/dyslexia_test/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures/'),
        ),
    ]
