# Generated by Django 4.2.20 on 2025-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dyslexiatestquestion_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='condition_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
    ]
