# Generated by Django 4.2.20 on 2025-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_condition_level'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autism',
            index=models.Index(fields=['autism_type'], name='main_autism_autism__fc55af_idx'),
        ),
        migrations.AddIndex(
            model_name='autism',
            index=models.Index(fields=['autism_level'], name='main_autism_autism__8e773c_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexia',
            index=models.Index(fields=['dyslexia_type'], name='main_dyslex_dyslexi_83a132_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexia',
            index=models.Index(fields=['dyslexia_level'], name='main_dyslex_dyslexi_ac0ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestquestion',
            index=models.Index(fields=['section'], name='main_dyslex_section_3cba53_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestquestion',
            index=models.Index(fields=['question_type'], name='main_dyslex_questio_254160_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestquestion',
            index=models.Index(fields=['hide_question_text'], name='main_dyslex_hide_qu_5cc875_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestquestion',
            index=models.Index(fields=['correct_answer'], name='main_dyslex_correct_c55263_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresponse',
            index=models.Index(fields=['user_profile'], name='main_dyslex_user_pr_824099_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresponse',
            index=models.Index(fields=['question'], name='main_dyslex_questio_29f770_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresponse',
            index=models.Index(fields=['is_correct'], name='main_dyslex_is_corr_c766ee_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresponse',
            index=models.Index(fields=['timestamp'], name='main_dyslex_timesta_05e156_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresponse',
            index=models.Index(fields=['response_time'], name='main_dyslex_respons_2926b3_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['user_profile'], name='main_dyslex_user_pr_b3ec78_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['total_score'], name='main_dyslex_total_s_e71542_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['completed_at'], name='main_dyslex_complet_d33f48_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['phonological_score'], name='main_dyslex_phonolo_352f25_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['surface_score'], name='main_dyslex_surface_62fab1_idx'),
        ),
        migrations.AddIndex(
            model_name='dyslexiatestresult',
            index=models.Index(fields=['visual_score'], name='main_dyslex_visual__f8fb97_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['condition_type'], name='main_userpr_conditi_e1f7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['condition_level'], name='main_userpr_conditi_0bf4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['board'], name='main_userpr_board_96c30c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['standard'], name='main_userpr_standar_02576f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['school'], name='main_userpr_school_abe0b8_idx'),
        ),
    ]
