# Generated by Django 4.2.20 on 2025-03-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_autism_main_autism_autism__fc55af_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='autism',
            name='main_autism_autism__fc55af_idx',
        ),
        migrations.RemoveIndex(
            model_name='autism',
            name='main_autism_autism__8e773c_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexia',
            name='main_dyslex_dyslexi_83a132_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexia',
            name='main_dyslex_dyslexi_ac0ed5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestquestion',
            name='main_dyslex_section_3cba53_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestquestion',
            name='main_dyslex_questio_254160_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestquestion',
            name='main_dyslex_hide_qu_5cc875_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestquestion',
            name='main_dyslex_correct_c55263_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresponse',
            name='main_dyslex_user_pr_824099_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresponse',
            name='main_dyslex_questio_29f770_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresponse',
            name='main_dyslex_is_corr_c766ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresponse',
            name='main_dyslex_timesta_05e156_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresponse',
            name='main_dyslex_respons_2926b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_user_pr_b3ec78_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_total_s_e71542_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_complet_d33f48_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_phonolo_352f25_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_surface_62fab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='dyslexiatestresult',
            name='main_dyslex_visual__f8fb97_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_conditi_e1f7e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_conditi_0bf4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_board_96c30c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_standar_02576f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_school_abe0b8_idx',
        ),
    ]
