# Generated by Django 4.2.20 on 2025-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_autism_main_autism_autism__fc55af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyslexiatestquestion',
            name='initial_or_assignment',
            field=models.CharField(blank=True, choices=[('initial', 'Initial'), ('assignment', 'Assignment')], max_length=20, null=True),
        ),
    ]
