# Generated by Django 4.2.20 on 2025-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyslexia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('history', 'History')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='materials/pdfs/')),
                ('vector_db_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('subject', 'title')},
            },
        ),
    ]
