# Generated by Django 4.2.20 on 2025-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyslexia', '0002_subjectmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterial',
            options={'ordering': ['subject', 'title']},
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='subject_pdfs/'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='vector_db_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
